network:
    version: 2
    renderer: networkd
    ethernets:
        eth0:
            optional: true
            addresses:
                - 192.168.90.10/24
            nameservers:
                search: [<your-domain]
                addresses: [192.168.90.1, 192.168.90.2]
            routes:
                - to: 0.0.0.0/0
                  via: 192.168.90.1
            link-local: [ ]
    wifis:
        wlan0:
            optional: true
            access-points:
                <your-ssid>:
                  password: "xxxx"
                  hidden: true
            addresses:
                - 192.168.90.10/24
            nameservers:
                search: [<your-domain>]
                addresses: [192.168.90.1, 192.168.90.2]
            routes:
                - to: 0.0.0.0/0
                  via: 192.168.90.1
                  metric: 50
            link-local: [ ]

